In [1]:
!pip install numpy

In [3]:
import numpy as np


In [12]:
serials=np.array([1,2,3,4,'sam'])
print(serials)

['1' '2' '3' '4' 'sam']


In [17]:
 #NUMPY ARRAYS:
#dimesions:
a=np.array(10)
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
d=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print('a dimesion : ',a.ndim)
print('b dimesion : ',b.ndim)
print('c dimesion : ',c.ndim)
print('d dimesion : ',d.ndim)


a dimesion :  0
b dimesion :  2
c dimesion :  3
d dimesion :  4


In [18]:
#shape:
print(a)
print('a shape : ',a.shape)
print(b)
print('b shape : ',b.shape)
print(c)
print('c shape : ',c.shape)
print(d)
print('d shape : ',d.shape)

10
a shape :  ()
[[1 2 3]
 [4 5 6]]
b shape :  (2, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
c shape :  (1, 3, 3)
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
d shape :  (1, 1, 4, 3)


In [19]:
#data type:
print(c.dtype)

int32


In [20]:
#type of variable:
print(type(a))

<class 'numpy.ndarray'>


In [21]:
#length:
len(b)

2

In [23]:
# Creating Numpyarrays:
# 1.using  arange fuction:
np.arange(1,11)



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [28]:
# 2.using eye function:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [38]:
# 3.using zero function:
np.zeros((3,2),dtype ='int')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [39]:
#using one fuction:
np.ones((3,2),dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [43]:
#using full function:
np.full((3,2),3,dtype='int')

array([[3, 3],
       [3, 3],
       [3, 3]])

In [45]:
#using diag function:
x=[1,2,3,4,5,6]
np.diag(x)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [56]:
# numpy reshape:
x=np.arange(1,11)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
1


In [61]:
n=x.reshape((5,2))
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
2


In [63]:
# convert into old dimesion
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)


(10,)
[ 1  2  3  4  5  6  7  8  9 10]
1


In [64]:
n=x.reshape(2,5)
print(n)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [66]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
#numpy array indexing
a=np.arange(2,17,2)
print(a)

[ 2  4  6  8 10 12 14 16]


In [69]:
#get second element from array
a[1]

4

In [74]:
#get 4,6,8 elements from the array
a[3:8:2]

array([ 8, 12, 16])

In [75]:
#2d array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
#get 3rd element from 3rd row
a[2,2]

9

In [78]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. 'a' have nested array.Understand the braket differences.
b[0][1][1]

5

In [88]:
#numpy array slicing
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:

a[5:]


array([ 6,  7,  8,  9, 10])

In [91]:
a[0:5]

array([1, 2, 3, 4, 5])

In [92]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
n=a.reshape((5,2))
print(n)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [96]:
a[1]

2

In [99]:
a[2]

3

In [100]:
a[9]

10

In [101]:
#numpy copy vs view
x1=np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
x2 = x1
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [128]:
x2[0] = 10
print(x2)

[10 10  2  3  4  5  6  7  8  9]


In [122]:
print(id(x1))
print(id(x2))

2698875829584
2698875829584


In [125]:
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
2698875829584
2698875829584


In [127]:
#view- if we change any element in one array(x1),another array (x3)also change 
x3 = x1.view()
x3

array([10, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [129]:
np.shares_memory(x1, x3)

True

In [131]:
x3[0]=100
x3

array([100,  10,   2,   3,   4,   5,   6,   7,   8,   9])

In [132]:
x1

array([100,  10,   2,   3,   4,   5,   6,   7,   8,   9])

In [133]:
print(id(x1))
print(id(x3))

2698875829584
2698876641104


In [136]:
#copy
x4=np.copy(x1)
x4

array([100,  10,   2,   3,   4,   5,   6,   7,   8,   9])

In [137]:
x4[-1]=900
x4

array([100,  10,   2,   3,   4,   5,   6,   7,   8, 900])

In [138]:
x1

array([100,  10,   2,   3,   4,   5,   6,   7,   8,   9])

In [140]:
np.shares_memory(x1,x4)

False

In [141]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
a>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [143]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [146]:
a[(a>4)&(a<10)]

array([5, 6, 7, 8, 9])

In [147]:
x1 == x2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [148]:
x1 != x2

array([False, False, False, False, False, False, False, False, False,
       False])

In [149]:
x1 == x4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [150]:
#transposing
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [155]:
n=a.reshape(2,5)
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [159]:
print(n.transpose())
print("-----------------")
print(n)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
-----------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
import numpy as np

In [4]:
a=[1,2,3,4,5,6]
print(a)

[1, 2, 3, 4, 5, 6]


In [11]:
b=[2,5,8,9,6,3]
print(b)

[2, 5, 8, 9, 6, 3]


In [12]:
np.insert(a,3,b)

array([1, 2, 3, 2, 5, 8, 9, 6, 3, 4, 5, 6])

In [13]:
np.delete(b,0)

array([5, 8, 9, 6, 3])

In [14]:
a

[1, 2, 3, 4, 5, 6]

In [16]:
(a,b)

([1, 2, 3, 4, 5, 6], [2, 5, 8, 9, 6, 3])

In [19]:
np.hstack((a,b))#with columns

array([1, 2, 3, 4, 5, 6, 2, 5, 8, 9, 6, 3])

In [20]:
np.vstack((a,b))#with rows

array([[1, 2, 3, 4, 5, 6],
       [2, 5, 8, 9, 6, 3]])

In [27]:
a=[[1,2,3],[4,5,6],[4,2,8]]

In [23]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [28]:
np.sum(a)

35

In [29]:
np.sum(a,axis=0)

array([ 9,  9, 17])

In [30]:
np.sum(a,axis=1)

array([ 6, 15, 14])

In [31]:
np.median(a)

4.0

In [32]:
np.mean(a)

3.888888888888889

In [34]:
np.max(a)

8

In [36]:
np.sort(a)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 8]])